stages:
  - build
  - deploy


build:
  image: python:3.8
  stage: build
  script:
    - python3 ./tools/provision
    - source zulip-api-py3-venv/Scripts/activate


deploy:
  image: node:16.16.0
  stage: deploy
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt  --token=$VERCEL_TOKEN

after_script:
  - zulip-botserver --config-file zuliprc-zoho --bot-name=zoho